# Manage capacity, not time

The most common requirment I've heard for remote workers is that they have good time management. 
Employers have a bit of a grade school attitude towards their employees, if you don't have people sitting at their desks, and there's nobody there monitoring whether they are actually doing work, how can you be sure that they are actually working?
Working remotely without this structure forces you to think about the outputs of labour rather than the inputs, 
because there's no real way to show your boss that you're working dilligently, the only thing you can be rewarded for is your output. 
Once you start thinking about work in this way it becomes clear that *capacity* not *time* is the rate limiting step for producing quality work. 
Even if you are not working terribly long hours you will tend to run out of capacity long before you run out of time.



## Don't work long hours
## Urgency destroys capacity
## Focus is precious
## Measure and improve capacity
### Sleep
### Focus
